### ISSUE TITLE
Unable to configure the extension

### ISSUE THREAD

**Issue by Dobrotescu** [thirdinsight/AutoMarkFolderRead#3]
I am using TB 91.11.0 (64 bits). I was happy to find this extension, as I was hitting exactly the problems it is trying to solve.

However, after installing it, the configuration screen showed all boxes unchecked, and when I tried to check Trash, a "Choose Application" pop-up asked me to "choose an application to open the moz-extension link" and indicated I should search it on my file system.

I have a number of customized properties (for privacy and no-nonsense), but, to my knowledge, none should interfere with add-ons (I have a few others working fine).

Any idea what can be done to make this add-on work?

**Comment by thirdinsight** [comment]
Hello,
thank you for your message!

The options (settings) were loaded and saved using `storage.sync`. That worked "on my machine" but it is the only thing i can imagine that might be the cause of anything. So I have changed the addon with **version 1.2** to use `storage.local` instead.
Could you try the new version?

Kind Regards

**Comment by Dobrotescu** [comment]
Hi,
Thanks for the fast reaction. Unfortunately, the behavior is the same. Here is some debug info:
1. When I enable the add-on:
    background: addon loaded background.js:5:10
    Result loaded from local storage: {} common.js:15:10
    Using default common folders: {"drafts":true,"trash":true,"templates":true,"junk":true} common.js:23:12
2. When I click on the wrench:
    Uncaught (in promise) ReferenceError: messenger is not defined
        loadCommonFoldersOptions moz-extension://561329c8-59dd-4a11-8371-bb044467b61b/js/common.js:13
        restoreOptions moz-extension://561329c8-59dd-4a11-8371-bb044467b61b/js/options.js:35
    common.js:13:16
3. When I try to enable Trash (all check boxes are empty):
    2147942487
I hope this helps somewhat.

This is my mother's computer I'm setting up and I'll have it only a few more days, so if there is any other info that might help you, just let me know.

**Comment by thirdinsight** [comment]
Hello,
sorry for the delay and thank you very much for the console output! That was very helpful.

The problem seems to be that "messenger" is undefined. I couldn't find anything why that is so. I use the same version (91.11).

I replaced "messenger" with "browser" with v1.3. Are you able to try it if it works now (hopefully)?

Best Regards!

**Comment by Dobrotescu** [comment]
First of all, I simplified my "use case" and I won't be using this extension. However, I find it potentially useful, so I did some more digging, as the v1.3 behaved the same way as the previous ones, and I also encountered a few other weird TB behaviours. There are four settings that caused my problems; you might be mostly interested in the last one, but the others may have some impact too (I didn't test all the 16 possible combinations).

1. **privacy.resistFingerprinting**: if set to true, it breaks many things, such as the ability to use non-Microsoft fonts, or the ability of the addons.thunderbird.net pages to offer '+ Add to Thunderbird' (it would only offer '+ Download Now').
2. **javascript.enabled**: if set to false, also breaks the ability of the addons.thunderbird.net pages to offer '+ Add to Thunderbird'.
3. **browser.tabs.remote.autostart**: if set to false, it breaks the TB's ability to handle addons.thunderbird.net links in the embedded browser (opens them in the default external one) - I had disabled this setting for the apparently archaic concept that one process should be good enough for an email client.
4. **extensions.webextensions.remote**: if set to false, **IT BREAKS YOUR EXTENSION'S CONFIGURATION FUNCTION** (and who knows what else) - I had this disabled for the same "one process" concept.

I don't know if this information will help you make your extension more general, but at least, after you test it, it should be good enough for a warning on your TB add-on page.

P.S.
_I don't want to abuse your time, but you seem handy at dealing with add-ons and I couldn't find a command-line or a generic add-on solution, so if you can think at an easy way to set and reset properties 2,3,4 (3 and 4 need a TB restart), or any generic set of properties, with an add-on, I would appreciate some kind of a sketch. I found some Mozilla references, such as  [Implement a settings page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Implement_a_settings_page), but I feel I'm far from really understanding what do I actually have to do._

**Comment by thirdinsight** [comment]
Hello,
thank you again for the detailed information!

With settings 3 and 4 I can reproduce exactly the error you described above ("Uncaught (in promise) ReferenceError: messenger is not defined"). Settings 1 and 2 seem to have no effect. And as you say, it will be a good idea to point it out on the add-on page.

There doesn't seem to be a "direct" way to read or change the extended settings (I haven't seen one), both with the WebExtension API of Thunderbird or with the extension API of Firefox (which can be used at least partially in Thunderbird add-ons). In the latter, there is one possibility but the "frame" is given by the extension API, it is not a direkt way. What I found there are [browserSettings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings) and [privacy](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy). There may be more.

**Comment by Dobrotescu** [comment]
Thanks for the heads-up.

Since applying the "one process" settings requires a TB restart, I 
imagine that an easy fix would be to use a simple script able to switch 
between two user.js files when starting TB. I'll look into that when 
I'll have the time.

Thanks again for your work and comments.
