### ISSUE TITLE
Doesn't work with my "Archive" folder

### ISSUE THREAD

**Issue by moxvallix** [thirdinsight/AutoMarkFolderRead#4]
I installed this addon hoping for it to auto mark email I archive as read.
However, when I archive emails, they are sent to a subfolder, labelled after the year the email was created eg. 2022.

This addon seemingly doesn't mark emails in these subfolders as read. I tried moving an email to the base Archives folder, and it was marked immediately, so the addon does seem to be working for the base folder, just not subfolders.

I am on Thunderbird Beta 102.0b8

Edit: Keeping this for context, see below for updated info.

**Comment by moxvallix** [comment]
Actually, I have figured out why it may not be working for me, and it may not be the subfolders like I first thought.

One of my inboxes uses "Archive" rather than "Archives". Having the ability to add custom folders / adding "Archive" as an option likely would fix this.

**Comment by thirdinsight** [comment]
Hello,
thank you very much for the info!

You are right, I forgot to consider the subfolders. I will change that.

The folder names shown in the options are internal names (called common types) of the WebExtension API (see https://webextension-api.thunderbird.net/en/102/folders.html#folders-mailfolder).

The actual folder names can be different.

In the account settings actual folders can be assigned to common types. (e.g.: When deleting a message, Move it to this folder).

It is not clear what exactly is meant by the displayed names in the options. I will document the options for this.

Kind Regards

**Comment by thirdinsight** [comment]
Hello,
I have adjusted the add-on so that now messages in subfolders are also marked as read.

It is also available as a setting in the options panel.

May I kindly ask you to test if the functionality is now as you expect?

Thanks!

**Comment by moxvallix** [comment]
I do believe it to be working! Thank you for your good work!
