### ISSUE TITLE
Reset Thunderbird new email notification in Windows tray

### ISSUE THREAD

**Issue by informatorius** [thirdinsight/AutoMarkFolderRead#6]
Would it be possible for this extension to also reset Thunderbird new email notification in Windows tray, when no new Email is available in not monitored folders? 

e.g. I get new Email to Junk folder and configured AutoMarkFolderRead to set Junk Folder emails to read. Then it should also reset Thunderbird Windows tray icon for new email if I did not get another Email to Inbox too.

e.g. If I get new Email to Inbox and new Email to Junk Folder and AutoMarkFolderRead is configured to set Junk Folder Emails to read. Then AutoMarkFolderRead should **not** reset Windows tray icon

**Comment by thirdinsight** [comment]
Hello,
I could not find a way to update the Windows system tray icon at all with the Web Extension API, either Thunderbird or FireFox. It seems to me that this is not possible.
I don't run thunderbird on Windows. As I understand it the system tray is displaying the total amount of unread emails (for all acounts?) This is analogous to the display of total amount of unread emails next to each account name. How I understand it this may be a bug in Thunderbird. If emails are marked as read by using  the Web Extension API (like in this add-on) then the total amount of unread emails should be updated automatically as the total amount next to the account name.

Best Regards!
